name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Build Package
      run: yarn build 

    - name: Run Lint
      run: yarn lint

    - name: Run Type Check
      run: yarn type-check
      
    - name: Run Tests
      run: yarn test
  
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Publish package on NPM 📦
      run: yarn publish --new-version ${{ github.event.release.tag_name }}
      env:
        NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}